### ISSUE TITLE
Example on Arduino Nano RP2040 Connect 

### ISSUE THREAD

**Issue by ajsb85** [sparkfun/SparkFun_ToF_Range_Finder-VL6180_Arduino_Library#7] opened 2021-06-02 16:34 UTC
I just want to report that the examples does not works with Arduino Nano RP2040 Connect.
Tested with Adafruit and Sparkfun breakout boards

![image](https://user-images.githubusercontent.com/663460/120517219-83654c80-c3d0-11eb-81d2-ca798fd693b9.png)
![image](https://user-images.githubusercontent.com/663460/120517381-b0196400-c3d0-11eb-934c-73eff9cc1e76.png)

References:

https://www.sparkfun.com/products/12785
https://www.adafruit.com/product/3316
https://store.arduino.cc/nano-rp2040-connect

**Comment by santaimpersonator** [comment] 2021-09-01 03:24
I am closing this issue because it sounds like a [general technical assistance](https://www.sparkfun.com/technical_assistance) request. Please create a post on our [forum](https://forum.sparkfun.com/) for technical assistance. Otherwise, if there is an actual issue within the library itself... feel free to reopen the issue and please provide the information below:

### Subject of the issue
Describe your issue in detail.

### Your workbench
* What development board or microcontroller are you using?
* What version of hardware or breakout board are you using? 
* How is the breakout board wired to your microcontroller?
* How is everything being powered?
* Are there any additional details that may help us help you?

### Steps to reproduce
Tell us how to reproduce this issue. Please post stripped down example code demonstrating your issue.

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

**Closed as completed by santaimpersonator** 2021-09-01 03:24 UTC
